### ISSUE TITLE
Error when calling rand_forest function with fit

### ISSUE THREAD

**Issue by tiagobrc** [BUStools/BUS_notebooks_R#1]
Hi, thanks for the nice notebooks for single-cell analysis.

following your slingshot dimension_reduction, the error is shown:

```
model <- rand_forest(mtry = 50, trees = 1200, min_n = 15) %>%
  set_engine("ranger", importance = "impurity", num.threads = 3) %>%
  fit(pseudotime ~ ., data = dat_train)
```

```
Error in fit.model_spec(., pseudotime ~ ., data = dat_train) : 
  formula_ is unknown
```

can you help me?

Thanks

Tiago

**Comment by lambdamoses** [comment]
This might be relevant: https://github.com/tidymodels/parsnip/issues/186 The notebook was made with the CRAN release version of `parsnip`, where `mode` can be left to be the default `"unknown"` in `rand_forest`. That GitHub issue seems relevant to the development version. I installed the development version of `parsnip` (0.0.3.9000), and reproduced your error. Specifying `mode = "regression"` in `rand_forest` solved the problem:

```
model <- rand_forest(mtry = 50, trees = 1200, min_n = 15, mode = "regression") %>%
  set_engine("ranger", importance = "impurity", num.threads = 3) %>%
  fit(pseudotime ~ ., data = dat_train)
```
